### ISSUE TITLE
Scroll window cuts off numbered callouts

### ISSUE THREAD

**Issue by cloojure** [pedestal/pedestal-docs#94] opened 2017-11-20 14:48 UTC
In this section of the guide:   http://pedestal.io/guides/your-first-api#_create_list  
the scroll window is not wide enough and cuts off the numbered "callout" bullet points #1 .. #5 (see image). Is there an asciidoctor param to make the window wider?

Alan
![screenshot from 2017-11-20 06-45-58](https://user-images.githubusercontent.com/7083783/33024045-da10f590-cdbe-11e7-812c-94e25259efd2.png)

**Comment by ddeaguiar** [comment] 2018-06-30 14:10
Closing this as it's old and I'm not able to reproduce.
<img width="919" alt="screen shot 2018-06-30 at 10 08 20 am" src="https://user-images.githubusercontent.com/5809/42125930-bf4329ac-7c4d-11e8-9562-823018667c71.png">

@cloojure reopen if it's still an issue for you.

**Closed by ddeaguiar** 2018-06-30 14:10 UTC
